### ISSUE TITLE
Google Spreadsheet Scripts - Putting spreadsheet data in a table format of the email body

### ISSUE THREAD

**Issue by dawiegriesel** [gsuitedevs/apps-script-dialog2sidebar#1]
`function sendEmails() {
  var sheet = SpreadsheetApp.getActiveSheet();     // there is only one sheet that uses a dataimport function to get the relevant data for the week
  var dataRange = sheet.getDataRange();  
  var data = dataRange.getValues();         //  fetch the values of for each row in the active range
  var emailAddress = 'dawie@wellnessodyssey.co.za';  // email address the mail needs to go to
  var message = dataRange.getDataTable(data);       // spreadsheet data in a table format
  var subject = sheet.getSheetName();                       // name of the sheet
  MailApp.sendEmail(emailAddress, subject, message);

}
`
I would like to include the data in the range in a table format as part of the body of the email to simplify reading the email. It comes through in a comma separated format that is hard to read.

Can anyone assist me with this please.

Kind regards

Dawie

**Comment by erickoledadevrel** [comment]
Please see the Apps Script support page for more information on how to get help: https://developers.google.com/apps-script/support
